apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-mhbl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-mhbl
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-mhbl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-mhbl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-mhbl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-rzbc-tenant/quarkus/devfile-sample-code-with-quarkus-mhbl@sha256:0f60eb0ba58eb12ce11ddf18296441b9ab52c3066c737099e7b322c7c60f298b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
