apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-mhbl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-rzbc-tenant/quarkus/devfile-sample-code-with-quarkus-mhbl@sha256:0f60eb0ba58eb12ce11ddf18296441b9ab52c3066c737099e7b322c7c60f298b
        name: my-java-quarkus
        resources: {}
status: {}
